SHELL:=/bin/bash
# PATH2Spack debería cambiarse por el path en el que esté el archivo setup-env.sh en su máquina
PATH2Spack = /workspaces/HPC/spack/share/spack/setup-env.sh
# PATH2Catch debería cambiarse por el path en el que estén los archivos libCatch2.a y libCatch2Main.a
PATH2Catch = /workspaces/HPC/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/catch2-3.4.0-vduvzwgafb2ywqkuakp5o3bnkzvh3663/lib

all: vector_main.x

%.x: %.o vector_ops.o
	source $(PATH2Spack); \
	spack load catch2; \
	g++ $$(pkg-config --cflags catch2) $^ -o $@

%.o: %.cpp
	source $(PATH2Spack); \
	spack load catch2; \
	g++ $$(pkg-config --cflags catch2) -c $<

test: vector_test.x
	./vector_test.x

vector_test.x: vector_test.o vector_ops.o
	g++ $^ -o $@ -L $(PATH2Catch) -l Catch2Main -l Catch2

clean:
	rm -f *.o *.x